_target_: navsim.agents.SeerDrive.SeerDrive_agent.SeerDriveAgent
_convert_: 'all'

config:
  _target_: navsim.agents.SeerDrive.configs.default.SeerDriveConfig
  _convert_: 'all'

trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  time_horizon: 4
  interval_length: 0.5

checkpoint_path: null
lr: 2e-4
